apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime-chatapp-backend-deployment
  labels:
    app: realtime-chatapp-backend
  namespace: realtime-chatapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realtime-chatapp-backend
  template:
    metadata:
      labels:
        app: realtime-chatapp-backend

    spec:
      containers:
        - name: realtime-chatapp-backend
          image: 023703348962.dkr.ecr.ap-south-1.amazonaws.com/realtime-chatapp-backend:ea3794d873bed9537959ea2b6e8911500b9acf03-4
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: chatapp-configmap
            